# Generated by Django 6.0 on 2026-02-21 06:42

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.utils.user_image_path
            ),
        ),
    ]
