# Generated by Django 6.0 on 2026-05-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
